use base ubuntu image to apply hugepages

diff --git a/scripts/deploy/actions/azstor-prereq.yaml b/scripts/deploy/actions/azstor-prereq.yaml
--- a/scripts/deploy/actions/azstor-prereq.yaml
+++ b/scripts/deploy/actions/azstor-prereq.yaml
@@ -16,10 +16,11 @@ spec:
       hostNetwork: true
       hostPID: true
       containers:
-      - image: docker.io/ramants17/azstor-prereq-linux:latest
+      - image: mcr.microsoft.com/oss/mirror/docker.io/library/ubuntu:18.04
         imagePullPolicy: Always
         name: *name
-        args: ["azstor-prereq"]
+        command: ["/bin/sh"]
+        args: ["-c", "/opt/actions/azstor-prereq.sh"]
         resources:
           requests: {}
           limits: {}
@@ -40,6 +41,7 @@ spec:
       - name: actions
         configMap:
           name: nsenter-actions
+          defaultMode: 0777
       - name: var
         hostPath:
           path: /var
@@ -52,12 +54,12 @@ metadata:
   labels:
     app: nsenter
 data:
-  azstor-prereq: |
+  enable-hugepages-and-nvme: |
     #!/usr/bin/env bash
     set -euo pipefail
     modprobe -a nvmet nvme-rdma nvme-fc nvmet-fc nvme-tcp nvmet-tcp nvme-fabrics
-    FILE=/var/run/azure-prereq
-    NOACTIONFILE=/var/run/azure-prereq-no-action
+    FILE=/var/run/azstor-prereq
+    NOACTIONFILE=/var/run/azstor-prereq-no-action
     if [ -f "$FILE" ]; then
       echo "$FILE exists." > $NOACTIONFILE
     else
@@ -70,4 +72,39 @@ data:
       systemctl restart kubelet
     fi
     sleep infinity
+  azstor-prereq.sh: |
+    #!/usr/bin/env bash
+    set -o errexit
+    set -o pipefail
+    set -o nounset
+
+    ACTION_FILE="/opt/actions/enable-hugepages-and-nvme"
+
+    if [[ ! -f "$ACTION_FILE" ]]; then
+        echo "Expected to find action file '$ACTION_FILE', but did not exist"
+        exit 1
+    fi
+
+    echo "Cleaning up stale actions"
+
+    rm -rf /mnt/actions/*
+
+    echo "Copying fresh actions"
+
+    cp -R /opt/actions/. /mnt/actions
+
+    echo "Executing nsenter"
+
+    nsenter -t 1 -m bash "${ACTION_FILE}"
+    RESULT="${PIPESTATUS[0]}"
+
+    if [ $RESULT -eq 0 ]; then
+        # Success.
+        rm -rf /mnt/actions/*
+        echo "Completed successfully!"
+        sleep infinity
+    else
+        echo "Failed during nsenter command execution"
+        exit 1
+    fi
 ---
